### ISSUE TITLE
How to stop member sync from calling sync_to_user()

### ISSUE THREAD

**Issue by devdavc** [christianwach/civicrm-wp-member-sync#55]
Have a situation where I need to stop the plugin to call `sync_to_user()`. Because it would call `civi_contact_id_get()` which then calls `synchronizeUFMatch()` if needed. I would specifically need to stop that as it recreates an already existing contact.
 I tried these.

```php
$civicrm = civi_wp();
remove_action( 'civi_wp_member_sync_refresh', [ $civicrm, 'schedule_callback' ] );
remove_action( 'civi_wp_member_sync_initialised', [ $civicrm, 'initialise' ], 1 );
remove_action( 'wp_login', [ $civicrm, 'sync_to_user' ], 10, 2 );

$userWp = get_userdata($ufID);
apply_filters('civi_wp_member_sync_user_should_be_synced', false, $userWp);
```

In Profile sync, this would work: `apply_filters('cwps/user/should_be_synced', false, $userWp, $individual);`

**Comment by christianwach** [comment]
@devdavc It seems that you're trying to disable sync for all WordPress Users... can I ask why you would do that and not just disable the plugin? BTW, in neither Profile Sync nor this plugin would your code work. You need to use `add_filter()` with a callback.

FYI this plugin specifically [unhooks CiviCRM's callbacks](https://github.com/christianwach/civicrm-wp-member-sync/blob/1d582b04f0752c6aa40a017e708dba7e4f18782e/includes/civi-wp-ms-users.php#L944) when it creates a WordPress User and [reapplies them](https://github.com/christianwach/civicrm-wp-member-sync/blob/1d582b04f0752c6aa40a017e708dba7e4f18782e/includes/civi-wp-ms-users.php#L985) when it's done. It also [creates the UFMatch entry](https://github.com/christianwach/civicrm-wp-member-sync/blob/1d582b04f0752c6aa40a017e708dba7e4f18782e/includes/civi-wp-ms-users.php#L890), so that CiviCRM knows that the User and Contact are linked. If you are getting new Contacts created each time `rule_apply()` runs, then something else is at play in your install.

**Comment by christianwach** [comment]
@devdavc Hmm, thinking about this a bit more... are you saying you have WordPress Users with no Contact in CiviCRM? FWIW, that's not the default way in which CiviCRM works - all Users have Contacts, but not all Contacts have Users. Is your situation that you want to prevent certain WordPress Users from having an associated CiviCRM Contact?

**Comment by devdavc** [comment]
@christianwach Hi. Thank you for the feedback. Will read more to this and try again. Seems like I am just making mistakes. The way you pinpoint logic gave me some ideas.
